services:
  otel:
    image: otel/opentelemetry-collector:0.25.0
    ports:
      - "6831:6831"
      - "14268:14268"
      - "4317:4317"
    volumes:
      - ./config/otel-collector.yaml:/config/otel-collector.yaml
    command:
      - --config=/config/otel-collector.yaml
    networks:
     - front 
     - back

  mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=thinks
      - MONGO_INITDB_ROOT_PASSWORD=kentik
    networks:
     - back

  tempo:
    image: grafana/tempo:0.7.0
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3100:3100"
      - "55680:55680"
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./example-data/tempo:/tmp/tempo
    networks:
     - back       
  
  grafana:
    image: grafana/grafana:7.5.4
    volumes:
      - ./config/datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - tempo
    networks:
     - front 
     - back

  api:
    container_name: api
    image: keeb/thinks-api
    environment:
      - AGENT_HOSTNAME=otel
      - MONGODB_PW=kentik
      - OTEL_PYTHON_LOG_CORRELATION=true
    ports:
      - "5000:5000"
    networks:
     - front
     - back
    depends_on:
      - otel-collector
      - mongo

  #ui:
  #  container_name: ui
  #  image: keeb/thinks-ui
  #  networks:
  #   - front
  # depends_on:
  #    - api

networks:
  front: {}
  back: {}
  
